use_frameworks!

platform :ios, '9.0'

target 'SDCycleScrollView_M_Example' do
  pod 'SDCycleScrollView_M', :path => '../'

  target 'SDCycleScrollView_M_Tests' do
    inherit! :search_paths

    
  end
end
